/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface Asset {
  // Unique identifier for the asset
  id: number;
  // Name of the asset
  name: string;
  // Category/type of the asset
  type: string;
  // Current status of the asset
  status: string;
}

export interface Error {
  // Error message
  message?: string;
  // Error code
  code?: string;
}
