/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface Projects {
  ProjectId?: number;
  Name: string;
  Description?: string;
  StartDate?: string;
  EndDate?: string;
  Status: string;
  Priority: string;
  Budget?: number;
  ProjectManagerEmail: string;
  CreatedBy: string;
  CreatedDate: string;
  IsActive: boolean;
}
