/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { Asset } from '../Models/AssetManagementTestAPIModel';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';

export class AssetManagementTestAPIService {
  private static readonly dataSourceName = 'asset-20management-20test-20api-5f39671246a0d64-c6fc231539dd189f';

  /**
   * Get all assets
   * Retrieves a list of all assets in the system
   */
  public static async GetAssets(): Promise<IOperationResult<Asset[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.executeAsync<void, Asset[]>({
      connectorOperation: {
        tableName: AssetManagementTestAPIService.dataSourceName,
        operationName: 'GetAssets',
      },
    });
    return result;
  }
}
